### ISSUE TITLE
unable to send test email

### ISSUE THREAD

**Issue by kannanwebtech** [magepal/magento2-gmail-smtp-app#104]
#### Actual behavior: Unable to send test email

ERROR :

Bummer!

5.7.14 <https://accounts.google.com/signin/continue?sarp?...............................................

Help me please

**Comment by srenon** [comment]
@kannanwebtech .... click on the link in the error message and follow the instruction

**Comment by ttn1185** [comment]
Link is unclickable due to error formating.

Bummer!

5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsq /> 5.7.14 Nn-oH0_0QMf3CIFZfY4kCac3TV1tAuyZzpQvtmUcrmqh0wlioSinmhRe1VGW0Ljb141UCD
5.7.14 xIe0bCzgJNjPbcCGLJgB8J6P8v90mlJlRirHI_Dp_dFiRCkwsSlIjiQr-H7OAhEO-IGVJd
5.7.14 MIXcQL6Q2H5kDpmLBZlGoTmMuTQj5wKlwrn6QlHS3o3UZRnxoXiMYMDyw7SQnhnTAKZ-5Q
5.7.14 YNb0xHctCWzEn7F_0w96LvVzZqOAo> Please log in via your web browser and
5.7.14 then try again.
5.7.14 Learn more at
5.7.14 https://support.google.com/mail/answer/78754 t68-v6sm9519424pfe.91 - gsmtp

**Comment by Tarek-Adra** [comment]
Turn On "Less secure app access" in your google account 

or check your emails (Google must send an email like "Review blocked sign-in attempt")
