### ISSUE TITLE
Error sending emails through the magepal module

### ISSUE THREAD

**Issue by guilhermetb** [magepal/magento2-gmail-smtp-app#122]
Magento version: 2.2.5

Edition (EE, CE, OS, etc): CE

Expected behavior:  User create an account on the site and confirmation email be sent to user

Actual behavior: Stores -> ADVANCED -> System -> Test email Server Configuration Settings
Email successfully sent 
but when user creates an account on the sending e-mail site the error occurs
[2018-08-20 15:21:21] main.CRITICAL: Relaying disallowed as Contato <contato@emporiobit.com.br>
 {"exception":"[object] (Magento\\Framework\\Exception\\MailException(code: 0): Relaying disallowed as Contato <contato@emporiobit.com.br>
 at /var/www/html/magento2/vendor/magepal/magento2-gmailsmtpapp/Plugin/Mail/TransportPlugin.php:121, Zend_Mail_Protocol_Exception(code: 553): Relaying disallowed as Contato <contato@emporiobit.com.br>
 at /var/www/html/magento2/vendor/magento/zendframework1/library/Zend/Mail/Protocol/Abstract.php:431)"} []
Email configured magepal noreply@emporiobit.com.br, e-mail sent through contato@emporiobit.com.br

Preconditions
Magento 2.2.5
PHP 7.0.30-0+deb9u1
mysql  Ver 15.1 Distrib 10.1.26-MariaDB

**Comment by srenon** [comment]
This error is not caused by our extension... See http://lmgtfy.com/?q=Relaying+disallowed+as

### Relaying disallowed error
When the email address (or login credentials) you have provided in the application does not match the email address (or credentials) of your account's outgoing server, you will see a 'Relaying Disallowed' error when you attempt to send an email. The SMTP client will not be able to send the email because of the email address mismatch. 

This can happen when an email address is used as default in a coded program or when you have misspelled the email address while configuring your email inbox. You will receive emails without any issues. To resolve the 'Relaying Disallowed' error, you need to correct the email address provided.
