### ISSUE TITLE
Wrong arguments

### ISSUE THREAD

**Issue by shinesoftware** [magepal/magento2-gmail-smtp-app#172]
Hello guys,

after installing the module by the composer tool (v.2.8.5) at my Magento ver. 2.3.5-p2 and then I try to add the credentials in the form:

![Selection_024](https://user-images.githubusercontent.com/1553035/93867713-bac01d00-fcc9-11ea-9e59-bb7335465012.jpg)

but I get this error:

`Fatal error: Uncaught TypeError: Argument 1 passed to Magento\Config\Model\Config::getOriginalFieldId() must be an instance of Magento\Config\Model\Config\Structure\Element\Group, instance of Magento\Config\Model\Config\Structure\Element\Field\Interceptor given, called in /var/www/html/magento23x.local/vendor/magento/module-config/Model/Config.php on line 279 and defined in /var/www/html/magento23x.local/vendor/magento/module-config/Model/Config.php:248 Stack trace: #0 /var/www/html/magento23x.local/vendor/magento/module-config/Model/Config.php(279): Magento\Config\Model\Config->getOriginalFieldId(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), 'use_separate_pr...') #1 /var/www/html/magento23x.local/vendor/magento/module-config/Model/Config.php(429): Magento\Config\Model\Config->getField('system/cron', 'template', 'use_separate_pr...') #2 /var/www/html/magento23x.local/vendor/magento/module-config/Model/Config.php(488): Magento\Config\Model\Config->_processGroup('template', Array, Array, 'system/c in /var/www/html/magento23x.local/vendor/magento/module-config/Model/Config.php on line 248`

any idea?

thanks

**Comment by srenon** [comment]
Sorry to hear that you are having issues, but this issue seems to be unrelated to our extension. Normally we do charge a fee to get involved in customer projects who are using our free extensions.

To solve your issue, please take a look at https://community.magento.com/t5/Magento-2-x-Technical-Issues/M2-3-5-Configuration-Saving-Error/td-p/453808 and please consider purchasing some of our other amazing extensions

We are trying to build up our Google Reviews. Do you mind giving us a quick review on Google? https://g.page/r/CXxKkgPhIg7TEAY/review

**Comment by shinesoftware** [comment]
Thanks @srenon we have solved the problem disabling all the external modules and seems that the error wasn't yours. Regards
